{% set name = "libint2" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    git_url: git@github.com:evaleev/libint.git           # [linux]
    git_url: https://github.com/evaleev/libint.git       # [osx]
    git_tag: 004f32e

build:
    number: 1                                            # [linux]
    binary_relocation: true
    skip: true                                           # [win]

requirements:
    build:
      - {{ compiler('cxx') }}
    host:
      - boost
      - eigen
      - gmp
      - mpfr
      
test:
    commands:
        # Verify library
        - test -f $PREFIX/lib/libint2$SHLIB_EXT
        # Inspect linkage
        - ldd -r -u $PREFIX/lib/libint2.so && return 0  # [linux]
        - ldd -v $PREFIX/lib/libint2.so                 # [linux]

about:
    home: https://github.com/evaleev/libint
    doc_url: https://github.com/evaleev/libint/wiki
    # doc_source_url:
    license: LGPL-3.0+
    license_url: https://opensource.org/licenses/LGPL-3.0+
    license_file: LICENSE
    license_family: LGPL
    summary: "Libint is a high-performance library for computing Gaussian integrals in quantum mechanics"

